### ISSUE TITLE
Kanban Setup for Full Capstone Project

### ISSUE THREAD

**Issue by MudasirSherwani** [MudasirSherwani/Book-an-Appointment#14]
## Our Team consists of 4 Members for the [Project](https://github.com/users/MudasirSherwani/projects/5/views/1) 👍 
1. [Abdul Saboor Sohaib](@SaboorSohaib) ✔️ 
2. [Mudasir Sherwani ](@MudasirSherwani)✔️ 
3. [Oluwatoyin Olaoye](@AbayomiOlaoye)✔️ 
4. [Zainab Al-Zubair](@Zainab-Alzubair)✔️ 

**We the team have done the Kanban setup please take a review** 
![image](https://user-images.githubusercontent.com/86018834/235972607-8aedd8b0-d9e7-44e2-ae1a-d037d25ff0cd.png)
![image](https://user-images.githubusercontent.com/86018834/235972765-5c6934a7-493f-47e0-a0fc-09aced41b86c.png)

**Comment by Meltrust** [comment]
Hi @MudasirSherwani,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been pointed, assigned, and have descriptions.✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
